/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Himidiri Himakanika
 */
public class MainController extends javax.swing.JFrame {

    /**
     * Creates new form MainController
     */
    public MainController() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/defensesystem/utils/icon.png")).getImage());

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - this.getWidth()) / 2;
        int y = screenSize.height - this.getHeight() - 100;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msgScrollPane = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        sendMsgTextField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        selectDefence = new javax.swing.JComboBox<>();
        areaClearCheckBox = new javax.swing.JCheckBox();
        soldierCountLbl = new javax.swing.JLabel();
        setSoldierCount = new javax.swing.JLabel();
        fuelAmountLbl = new javax.swing.JLabel();
        setAmmoAmount = new javax.swing.JLabel();
        ammoAmountLbl = new javax.swing.JLabel();
        setFuelAmount = new javax.swing.JLabel();
        sendPrivateCheckBox = new javax.swing.JCheckBox();
        positionLbl = new javax.swing.JLabel();
        positionSlider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainController");
        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(820, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 500));
        jPanel1.setLayout(null);

        msgTextArea.setBackground(new java.awt.Color(0, 0, 0));
        msgTextArea.setColumns(20);
        msgTextArea.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        msgTextArea.setForeground(new java.awt.Color(255, 255, 255));
        msgTextArea.setRows(5);
        msgScrollPane.setViewportView(msgTextArea);

        jPanel1.add(msgScrollPane);
        msgScrollPane.setBounds(390, 80, 390, 200);

        sendMsgTextField.setBackground(new java.awt.Color(51, 51, 51));
        sendMsgTextField.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        sendMsgTextField.setForeground(new java.awt.Color(255, 255, 255));
        sendMsgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMsgTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(sendMsgTextField);
        sendMsgTextField.setBounds(390, 300, 300, 40);

        sendBtn.setBackground(new java.awt.Color(0, 102, 102));
        sendBtn.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Send");
        jPanel1.add(sendBtn);
        sendBtn.setBounds(700, 300, 80, 40);

        selectDefence.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        selectDefence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarine" }));
        selectDefence.setMinimumSize(new java.awt.Dimension(150, 30));
        selectDefence.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(selectDefence);
        selectDefence.setBounds(390, 20, 180, 40);

        areaClearCheckBox.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        areaClearCheckBox.setForeground(new java.awt.Color(0, 204, 204));
        areaClearCheckBox.setText("Area Clear");
        areaClearCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaClearCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(areaClearCheckBox);
        areaClearCheckBox.setBounds(250, 60, 110, 50);

        soldierCountLbl.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        soldierCountLbl.setForeground(new java.awt.Color(255, 255, 255));
        soldierCountLbl.setText("Soldier Count : ");
        soldierCountLbl.setMaximumSize(new java.awt.Dimension(100, 20));
        soldierCountLbl.setMinimumSize(new java.awt.Dimension(100, 20));
        soldierCountLbl.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(soldierCountLbl);
        soldierCountLbl.setBounds(10, 20, 130, 50);

        setSoldierCount.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        setSoldierCount.setForeground(new java.awt.Color(255, 255, 255));
        setSoldierCount.setText("2000");
        setSoldierCount.setMaximumSize(new java.awt.Dimension(30, 20));
        setSoldierCount.setMinimumSize(new java.awt.Dimension(30, 20));
        setSoldierCount.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(setSoldierCount);
        setSoldierCount.setBounds(140, 20, 80, 50);

        fuelAmountLbl.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        fuelAmountLbl.setForeground(new java.awt.Color(255, 255, 255));
        fuelAmountLbl.setText("Fuel Amount : ");
        fuelAmountLbl.setMaximumSize(new java.awt.Dimension(100, 20));
        fuelAmountLbl.setMinimumSize(new java.awt.Dimension(100, 20));
        fuelAmountLbl.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(fuelAmountLbl);
        fuelAmountLbl.setBounds(10, 60, 130, 50);

        setAmmoAmount.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        setAmmoAmount.setForeground(new java.awt.Color(255, 255, 255));
        setAmmoAmount.setText("3444");
        setAmmoAmount.setMaximumSize(new java.awt.Dimension(30, 20));
        setAmmoAmount.setMinimumSize(new java.awt.Dimension(30, 20));
        setAmmoAmount.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(setAmmoAmount);
        setAmmoAmount.setBounds(140, 100, 80, 50);

        ammoAmountLbl.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        ammoAmountLbl.setForeground(new java.awt.Color(255, 255, 255));
        ammoAmountLbl.setText("Ammo Amount :");
        ammoAmountLbl.setMaximumSize(new java.awt.Dimension(100, 20));
        ammoAmountLbl.setMinimumSize(new java.awt.Dimension(100, 20));
        ammoAmountLbl.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(ammoAmountLbl);
        ammoAmountLbl.setBounds(10, 100, 130, 50);

        setFuelAmount.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        setFuelAmount.setForeground(new java.awt.Color(255, 255, 255));
        setFuelAmount.setText("3444");
        setFuelAmount.setMaximumSize(new java.awt.Dimension(30, 20));
        setFuelAmount.setMinimumSize(new java.awt.Dimension(30, 20));
        setFuelAmount.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(setFuelAmount);
        setFuelAmount.setBounds(140, 60, 70, 50);

        sendPrivateCheckBox.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        sendPrivateCheckBox.setForeground(new java.awt.Color(0, 204, 204));
        sendPrivateCheckBox.setText("Send Private");
        sendPrivateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPrivateCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(sendPrivateCheckBox);
        sendPrivateCheckBox.setBounds(660, 20, 150, 40);

        positionLbl.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        positionLbl.setForeground(new java.awt.Color(255, 255, 255));
        positionLbl.setText("Position");
        positionLbl.setMaximumSize(new java.awt.Dimension(100, 20));
        positionLbl.setMinimumSize(new java.awt.Dimension(100, 20));
        positionLbl.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(positionLbl);
        positionLbl.setBounds(390, 350, 130, 50);

        positionSlider.setBackground(new java.awt.Color(0, 204, 204));
        positionSlider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        positionSlider.setForeground(new java.awt.Color(255, 255, 255));
        positionSlider.setMajorTickSpacing(20);
        positionSlider.setMinorTickSpacing(10);
        positionSlider.setPaintLabels(true);
        positionSlider.setPaintTicks(true);
        positionSlider.setSnapToTicks(true);
        jPanel1.add(positionSlider);
        positionSlider.setBounds(380, 380, 410, 60);

        infoTextArea.setBackground(new java.awt.Color(0, 0, 0));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        infoTextArea.setForeground(new java.awt.Color(255, 255, 255));
        infoTextArea.setRows(5);
        jScrollPane1.setViewportView(infoTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 350, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaClearCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaClearCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaClearCheckBoxActionPerformed

    private void sendMsgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMsgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMsgTextFieldActionPerformed

    private void sendPrivateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPrivateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendPrivateCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammoAmountLbl;
    private javax.swing.JCheckBox areaClearCheckBox;
    private javax.swing.JLabel fuelAmountLbl;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane msgScrollPane;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JLabel positionLbl;
    private javax.swing.JSlider positionSlider;
    private javax.swing.JComboBox<String> selectDefence;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField sendMsgTextField;
    private javax.swing.JCheckBox sendPrivateCheckBox;
    private javax.swing.JLabel setAmmoAmount;
    private javax.swing.JLabel setFuelAmount;
    private javax.swing.JLabel setSoldierCount;
    private javax.swing.JLabel soldierCountLbl;
    // End of variables declaration//GEN-END:variables
}
